antico/config/routes.rb
Rails.application.routes.draw do
  resources :pizzas

end

antico/app/models/pizza.rb
class Pizza < ActiveRecord::Base
end

antico/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

antico/app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  before_action :set_pizza, only: [:show, :edit, :update, :destroy]

  # GET /pizzas
  # GET /pizzas.json
  def index
    @pizzas = Pizza.all
  end

  # GET /pizzas/1
  # GET /pizzas/1.json
  def show
  end

  # GET /pizzas/new
  def new
    @pizza = Pizza.new
  end

  # GET /pizzas/1/edit
  def edit
  end

  # POST /pizzas
  # POST /pizzas.json
  def create
    @pizza = Pizza.new(pizza_params)

    respond_to do |format|
      if @pizza.save
        format.html { redirect_to @pizza, notice: 'Pizza was successfully created.' }
        format.json { render :show, status: :created, location: @pizza }
      else
        format.html { render :new }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pizzas/1
  # PATCH/PUT /pizzas/1.json
  def update
    respond_to do |format|
      if @pizza.update(pizza_params)
        format.html { redirect_to @pizza, notice: 'Pizza was successfully updated.' }
        format.json { render :show, status: :ok, location: @pizza }
      else
        format.html { render :edit }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizzas/1
  # DELETE /pizzas/1.json
  def destroy
    @pizza.destroy
    respond_to do |format|
      format.html { redirect_to pizzas_url, notice: 'Pizza was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pizza
      @pizza = Pizza.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pizza_params
      params.require(:pizza).permit(:name, :description, :price)
    end
end

antico/app/helpers/application_helper.rb
module ApplicationHelper
end

antico/app/helpers/pizzas_helper.rb
module PizzasHelper
end

antico/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Antico</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

antico/app/views/pizzas/_form.html.erb
<%= form_for(@pizza) do |f| %>
  <% if @pizza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pizza.errors.count, "error") %> prohibited this pizza from being saved:</h2>

      <ul>
      <% @pizza.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

antico/app/views/pizzas/edit.html.erb
<h1>Editing Pizza</h1>

<%= render 'form' %>

<%= link_to 'Show', @pizza %> |
<%= link_to 'Back', pizzas_path %>

antico/app/views/pizzas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pizzas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pizzas.each do |pizza| %>
      <tr>
        <td><%= pizza.name %></td>
        <td><%= pizza.description %></td>
        <td><%= pizza.price %></td>
        <td><%= link_to 'Show', pizza %></td>
        <td><%= link_to 'Edit', edit_pizza_path(pizza) %></td>
        <td><%= link_to 'Destroy', pizza, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pizza', new_pizza_path %>

antico/app/views/pizzas/new.html.erb
<h1>New Pizza</h1>

<%= render 'form' %>

<%= link_to 'Back', pizzas_path %>

antico/app/views/pizzas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pizza.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pizza.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @pizza.price %>
</p>

<%= link_to 'Edit', edit_pizza_path(@pizza) %> |
<%= link_to 'Back', pizzas_path %>